#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

# Community cookbooks
cookbook 'vim', '~> 2.0.0'

# Custom cookbooks
cookbook 'dotfiles', path: 'custom/cookbooks/dotfiles'
cookbook 'ubuntu', path: 'custom/cookbooks/ubuntu'
