#!/usr/bin/env bash
cwd=$(pwd)
cd $HOME/.chef

# Pull latest version
git pull origin master

# Install cookbooks
librarian-chef install

# Run Chef client
echo "{\"user\":\"$USER\"}" | sudo chef-client -z -j /dev/stdin

cd $cwd
